platform :ios, '10.0'
use_frameworks!

target 'Alertify_Example' do
  pod 'Alertify', :path => '../'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.2'
        end
    end
end
